# Branch Protection Configuration for QuantumCoin
# This ensures only ci + perf are required and both must be green

# GitHub CLI command to apply:
# gh api repos/aeonith/quantumcoin-ui-/branches/main/protection \
#   --method PUT \
#   --field required_status_checks='{"strict":true,"contexts":["ci","perf / performance-gates (Required)"]}' \
#   --field enforce_admins=true \
#   --field required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true}' \
#   --field restrictions=null

required_checks:
  - "ci"  # Main CI workflow (tests, lint, coverage, security)
  - "perf / performance-gates (Required)"  # Performance gates workflow

settings:
  strict: true
  enforce_admins: true
  required_approving_reviews: 1
  dismiss_stale_reviews: true
