[package]
name = "quantumcoin-backend"
version = "0.1.0"
edition = "2021"
authors = ["Aeonith <aeonith@quantumcoincrypto.com>"]
description = "QuantumCoin™ backend API"
license = "MIT"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["form", "fs", "json", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
pqcrypto-dilithium = "0.3"
pqcrypto-traits = "0.3"
sha2 = "0.10"