[package]
name = "quantumcoin"
version = "1.0.0"
edition = "2021"

[dependencies]
pqcrypto-dilithium = "0.3"
pqcrypto-traits = "0.3"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
rand = "0.8"
uuid = { version = "1", features = ["v4"] }