[package]
name = "quantumcoin"
version = "0.1.0"
edition = "2021"
authors = ["Aeonith <aeonith@quantumcoincrypto.com>"]
description = "Quantum-resistant blockchain with web API"
license = "MIT"

[dependencies]
actix-web = "4.5"
tokio = { version = "1.37", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
pqcrypto-dilithium = "0.3.0"
pqcrypto-traits = "0.3.0"