[package]
name = "quantumcoin"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pqcrypto-dilithium = "0.3"
pqcrypto-traits = "0.3"
base64 = "0.21"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

# Internal modules
once_cell = "1.18"
lazy_static = "1.4"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"