[package]
name = "quantumcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
actix-files = "0.6.2"
actix-cors = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21.0"
pqcrypto-dilithium = "0.3.3"
pqcrypto-traits = "0.3.5"
chrono = "0.4"
rand = "0.8.5"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4"] }
futures-util = "0.3"
once_cell = "1.18"
lazy_static = "1.4.0"
sha2 = "0.10"
anyhow = "1"
hex = "0.4"
argon2 = "0.5"
rand_core = "0.6"
jsonwebtoken = "9.2"
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "sqlite", "macros"] }
otpauth = "0.5"
qrcode = "0.12"