[package]
name = "quantumcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21.0"
pqcrypto-dilithium = "0.3.0"
pqcrypto-traits = "0.3.5"
chrono = "0.4"
uuid = { version = "1.4", features = ["v4"] }
sha2 = "0.10"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
futures = "0.3"
lazy_static = "1.4"
parking_lot = "0.12"