[package]
name = "quantumcoin"
version = "2.0.0"
edition = "2021"
authors = ["Aeonith <aeonith@quantumcoincrypto.com>"]
description = "QuantumCoin™ - A quantum-resistant cryptocurrency"
license = "MIT"

[dependencies]
# Async runtime
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "sync", "time"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Cryptography
pqcrypto-dilithium = "0.3.3"
pqcrypto-traits = "0.3.5"
sha2 = "0.10"
sha3 = "0.10"
blake3 = "1.5"
base64 = "0.21.0"
rand = "0.8.5"
rand_core = "0.6"
argon2 = "0.5"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Threading and concurrency
parking_lot = "0.12"
crossbeam = "0.8"
rayon = "1.8"

# Utilities
uuid = { version = "1", features = ["v4", "serde"] }
hex = "0.4"
anyhow = "1"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# CLI
clap = { version = "4.0", features = ["derive"] }

# Optional database support
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "sqlite", "postgres", "macros", "json", "migrate"], optional = true }

# Optional networking
reqwest = { version = "0.11", features = ["json"], optional = true }

[features]
default = ["database"]
database = ["sqlx"]
web = ["reqwest"]

[[bin]]
name = "quantumcoin"
path = "src/main.rs"
