[package]
name = "quantumcoin-backend"
version = "0.1.0"
edition = "2021"
authors = ["Aeonith <aeonith@quantumcoincrypto.com>"]
description = "QuantumCoin™ backend API"
license = "MIT"

[dependencies]
rocket = { version = "0.5.0-rc.3", features = ["json", "form", "fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
sha2 = "0.10"
pqcrypto-dilithium = "0.5.0"
pqcrypto-traits = "0.3.0"