[package]
name = "quantumcoin-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"  # ✅ Stable Rocket release
rocket_dyn_templates = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.3", features = ["v4"] }
log = "0.4"
env_logger = "0.10"
tokio = { version = "1.32", features = ["full"] }
warp = "0.3"

# ✅ Quantum-safe crypto
pqcrypto-dilithium = "0.3"
pqcrypto-traits = "0.3"

# ✅ SHA-256 digest
sha2 = "0.10"

# ✅ File I/O
base64 = "0.21"
hex = "0.4"

# Optional: use for password input if needed
# rpassword = "7.0"

# Optional: For testing or JSON file save/load
serde_yaml = "0.9"