[workspace]
members = [
    "crates/node",
    "crates/wallet",
    "crates/ai-sentinel",
    "crates/genesis",
    "crates/validation",
    "crates/p2p",
    "backend",
    "stress-test"
]
resolver = "2"

[workspace.package]
version = "2.0.0"
edition = "2021"
authors = ["Aeonith <aeonith@quantumcoincrypto.com>"]
license = "MIT"
repository = "https://github.com/aeonith/quantumcoin-ui-"

[workspace.dependencies]
# Async runtime
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "sync", "time"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Cryptography - CANONICAL VERSION LOCKED
pqcrypto-dilithium = "0.3.3"
pqcrypto-traits = "0.3.5" 
sha2 = "0.10"
sha3 = "0.10"
blake3 = "1.5"
base64 = "0.21.0"
rand = "0.8.5"
rand_core = "0.6"
argon2 = "0.5"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Threading and concurrency  
parking_lot = "0.12"
crossbeam = "0.8"
rayon = "1.8"

# Utilities
uuid = { version = "1", features = ["v4", "serde"] }
hex = "0.4"
anyhow = "1"
thiserror = "1.0"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = "0.3"

# CLI
clap = { version = "4.0", features = ["derive"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "sqlite", "postgres", "macros", "json", "migrate"] }

# Web/HTTP
axum = "0.7"
tower = "0.4"
tower-http = "0.5"
reqwest = { version = "0.11", features = ["json"] }

# Testing
proptest = "1.4"

# Additional dependencies for new crates
dashmap = "5.5"
lru = "0.12" 
priority-queue = "1.3"
dns-lookup = "2.0"
socket2 = "0.5"
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
statistical = "1.0"
candle-core = "0.4"
candle-nn = "0.4"
candle-transformers = "0.4"
nalgebra = "0.32"
ndarray = "0.15"
plotters = "0.3"
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }
tempfile = "3.8"

# TOML parsing
toml = "0.8"

# HTTP server and client
hyper = { version = "0.14", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }

# Command line interface
clap = { version = "4.0", features = ["derive"] }

[[bin]]
name = "quantumcoin-node"
path = "src/bin/quantumcoin-node.rs"

[[bin]]
name = "quantumcoin-wallet"  
path = "src/bin/quantumcoin-wallet.rs"

[[bin]]
name = "quantumcoin-explorer"
path = "src/bin/quantumcoin-explorer.rs"

[package]
name = "quantumcoin"
version = "2.0.0"
edition = "2021"
authors = ["Aeonith <aeonith@quantumcoincrypto.com>"]
license = "MIT"
description = "Post-quantum cryptocurrency with live mainnet"
repository = "https://github.com/aeonith/quantumcoin-ui-"
keywords = ["cryptocurrency", "blockchain", "post-quantum", "dilithium"]
categories = ["cryptography", "network-programming"]

[dependencies]
# All workspace dependencies are included above

# Network dependencies for P2P
rustls = "0.23"
tokio-rustls = "0.26"
webpki-roots = "0.26"
hickory-resolver = "0.24"
snow = "0.9"
x25519-dalek = "2.0"
futures = "0.3"

# Main QuantumCoin package
[package]
name = "quantumcoin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
pqcrypto-dilithium = { workspace = true }
pqcrypto-traits = { workspace = true }
blake3 = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
argon2 = { workspace = true }
base64 = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
sqlx = { workspace = true }
futures = { workspace = true }
crc32fast = "1.3"
tempfile = { workspace = true }
proptest = { workspace = true }
rayon = { workspace = true }

# Real QuantumCoin crate dependencies
quantumcoin-node = { path = "crates/node" }
quantumcoin-wallet = { path = "crates/wallet" }
quantumcoin-genesis = { path = "crates/genesis" }
quantumcoin-validation = { path = "crates/validation" }
quantumcoin-p2p = { path = "crates/p2p" }

[[bin]]
name = "quantumcoin-real"
path = "src/main_real.rs"
