[package]
name = "quantumcoin-backend"
version = "0.1.0"
edition = "2021"
authors = ["Aeonith <aeonith@quantumcoincrypto.com>"]
description = "QuantumCoin™ backend API"
license = "MIT"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json", "tls"] }
rocket_dyn_templates = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread"] }
base64 = "0.21"
uuid = { version = "1", features = ["v4"] }
mime = "0.3"
form_urlencoded = "1.2"
time = "0.3"