[network]
name = "QuantumCoin"
symbol = "QC"
decimals = 8
version = "1.0.0"

[consensus]
hash_function = "sha256d"
target_block_time_secs = 600
difficulty_adjustment = "ASERT"
asert_half_life_secs = 2592000   # 30 days

[supply]
max_supply_sats = 2200000000000000  # 22,000,000 × 100,000,000
halving_interval_blocks = 105120      # ~2 years @ 10 min
premine_sats = 0

[txpolicy]
max_tx_size = 100000
min_fee_per_kb_sats = 1000
dust_threshold_sats = 546
max_inputs = 32
max_outputs = 32
coinbase_maturity = 100

[revstop]
window_blocks = 30
