version: "3.9"
services:
  node:
    build: ./crates/node
    ports: ["8545:8545"]
    restart: always

  explorer-api:
    build: ./services/explorer-api
    environment:
      - NODE_RPC_URL=http://node:8545
    ports: ["8082:8080"]
    depends_on:
      - node
    restart: always

  ai:
    build: ./services/ai-daemon
    ports: ["8081:8000"]
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:8000/health"]
      interval: 5s
      timeout: 2s
      retries: 20
    restart: always

  ui:
    build: ./apps/ui
    environment:
      - NEXT_PUBLIC_AI_URL=http://ai:8000
      - NEXT_PUBLIC_EXPLORER_URL=http://explorer-api:8080
      - NEXT_PUBLIC_BUILD_ID=${GITHUB_SHA:-local}
    ports: ["3000:3000"]
    depends_on:
      ai: { condition: service_healthy }
      explorer-api: { condition: service_started }
    restart: always
