# QuantumCoin Production Configuration

[server]
host = "0.0.0.0"
port = 8080
workers = 8
keep_alive = 75
client_timeout = 5000
client_shutdown = 5000

[database]
path = "./data/quantumcoin_production.db"
max_connections = 32
connection_timeout = 5000
cache_size_mb = 256
wal_mode = true
auto_vacuum = true

[security]
jwt_secret = "quantum-production-ultra-secure-key-2024-change-in-production"
auth_token_expiry = 3600
rate_limit_requests = 1000
rate_limit_window = 60
quantum_security_level = 5
enable_2fa = true

[logging]
level = "info"
file_output = true
file_path = "./logs/quantumcoin_production.log"
max_file_size_mb = 50
max_files = 10
json_format = false

[performance]
max_transactions_per_block = 50000
target_block_time_ms = 500
max_pending_transactions = 100000
cache_ttl_seconds = 300
enable_parallel_processing = true
batch_size = 5000

[quantum]
enable_quantum_crypto = true
security_level = 5
key_rotation_interval = 86400
enable_quantum_entanglement = true
quantum_consensus_threshold = 0.67
