services:
  - type: web
    name: quantumcoin-production
    env: rust
    region: oregon
    plan: starter
    buildCommand: |
      rustup update stable
      rustup default stable
      mkdir -p data
      cargo build --release
    startCommand: ./target/release/quantumcoin
    envVars:
      - key: QTC_ENV
        value: production
      - key: QTC_SERVER_HOST
        value: 0.0.0.0
      - key: QTC_LOG_LEVEL
        value: info
      - key: QTC_DATABASE_PATH
        value: /opt/render/project/src/data/quantumcoin_production.db
      - key: QTC_JWT_SECRET
        generateValue: true
      - key: QTC_WORKERS
        value: 4
      - key: RUST_LOG
        value: info
    disk:
      name: quantumcoin-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    healthCheckPath: /api/v1/health