services:
  - type: web
    name: quantumcoin-backend
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/quantumcoin
    envVars:
      - key: PORT
        value: 8080