services:
  - type: web
    name: quantumcoin-backend
    runtime: rust
    buildCommand: "cargo build --release"
    startCommand: "./target/release/quantumcoin-backend"
    env: 
      - key: RUST_LOG
        value: info
    plan: free